Added `adjustUrl` function
maptiler/maptiler-geocoding-control pull request #71
Opened 2024-12-05 19:24 UTC by zdila

## Objective
Added `adjustUrl` function replacing less universal `adjustUrlQuery` function.

## Description
`adjustUrl` receives complete URL which also enables to read and/or update search query.

2024-12-06 09:05 UTC, petr-hajek requested changes

2024-12-06 09:05 UTC, petr-hajek commented on src/types.ts
> +   * Default value is empty function.
Please add some example how to use

2024-12-06 09:31 UTC, zdila commented
example added in 9f3bfe34bf6a706e68dd11059ff6c84237c1515a

2024-12-06 09:35 UTC, zdila commented on src/types.ts
> +   * Default value is empty function.
See 9f3bfe34bf6a706e68dd11059ff6c84237c1515a

2024-12-06 20:23 UTC, petr-hajek commented on src/types.ts
> +   * Default value is empty function.
Thanks, this will probably be better to add to the docs than here

2024-12-09 14:07 UTC, petr-hajek approved these changes
After discussion, we will go ahead with this solution for now, but we will try to figure out some new user-friendly default for reverse geocoding (possibly something to reflect user's zoom level). We'll make a docs to explain to users how to adjust reverse geocoding using adjustUrl function

2024-12-09 14:24 UTC, merged