GO-852 implemented separate options for reverse geocoding
maptiler/maptiler-geocoding-control pull request #79
Opened 2024-12-23 16:05 UTC by zdila

GO-852

## Objective
Separate options (`limit`, `types`, `excludeTypes`) for reverse geocoding.

## Description
What changed, how and why?

### Acceptance
How were changes tested?

2025-01-02 14:20 UTC, petr-hajek requested changes

2025-01-02 14:20 UTC, petr-hajek commented on src/types.ts
> +  // TODO use reasonable types (see GO-729)
I don't think this is good to have for everyone to see in the autocomplete in their IDE :)

2025-01-02 16:00 UTC, petr-hajek requested changes

2025-01-02 16:00 UTC, petr-hajek commented on src/GeocodingControl.svelte
> +      }
this is strange, so if I set `limit:5` which is the default I am getting this warning (unless I change the `reverseGeocodingTypes` to single item array)
Also the description of the `reverseGeocodingLimit` should mention all this.
Why does `reverseGeocodingLimit` need to be same as limit by default? `reverseGeocodingLimit` is a special case since it needs to be coupled by `reverseGeocodingTypes` being single item.

2025-01-02 16:00 UTC, petr-hajek commented on src/GeocodingControl.svelte
> +      }
And if I set types to `poi` for example and not update `limit` or `reverseGeocodingLimit` it always returns one result as default, not 5

2025-01-02 20:25 UTC, zdila commented on src/types.ts
> +  // TODO use reasonable types (see GO-729)
`//` coment is not JSDoc and in my IDE (vscode) it does not appear. Which IDE do you use?

2025-01-02 20:27 UTC, zdila commented on src/GeocodingControl.svelte
> +      }
> Why does `reverseGeocodingLimit` need to be same as `limit` by default?

Backward compatibility, unless we want to bump the major version. Should we?

Please propose here more suitable defaults / logic also *`types`  and *`limit`.

2025-01-03 08:46 UTC, petr-hajek commented on src/types.ts
> +  // TODO use reasonable types (see GO-729)
oh sorry, I missed it's out of the jsdoc

2025-01-03 10:13 UTC, petr-hajek commented on src/GeocodingControl.svelte
> +      }
Is it documented anywhere that the `limit` currently works for reverse only if there's just one item in the type array & limit is set to something else than undefined?

Currently (even before these changes):
```
enableReverse: 'always',
types: ['poi']
```
returns always just **one** result for reverse geocoding, although normal geocoding returns **5** results
the only way how to get `limit` working for reverse geocoding was
```
enableReverse: 'always',
types: ['poi'],
limit: 5
```
So IMO if `reverseGeocodingLimit` should fallback to `limit`, in case neither of them is defined it should return 5 results for reverse gc (in case types or reverseGeocodingTypes have one item). 
It should also mention in the description of `reverseGeocodingLimit` that it only works for single type

2025-01-08 11:11 UTC, zdila commented on src/GeocodingControl.svelte
> +      }
Please re-review.

2025-01-08 15:23 UTC, petr-hajek requested changes

2025-01-08 15:23 UTC, petr-hajek commented on src/types.ts
> +   * Default: Value of the `limit` option if set, or `1` for a single effective type.
@zdila Thanks a lot for your changes. I had a bit of trouble understanding this. Could it be:
 Default: Value of the `limit` option if set, or `1` for each effective type otherwise.

2025-01-08 15:41 UTC, zdila commented on src/types.ts
> +   * Default: Value of the `limit` option if set, or `1` for a single effective type.
What do you mean by _each effective type_?

Effective type it what goes to `type=` URL parameter or all default types if no `type=` parameter is in URL.. (`excludeTypes=true` in URL also alters effective types). So in other words, it is types that geocoder will consider internally during the query.

So default here is verbosely:
- if `limit` opion is set then use its value
- if effective type is a single value then `1`
- otherwise it (limit) is not used because then it makes no sense

2025-01-08 16:43 UTC, petr-hajek commented on src/types.ts
> +   * Default: Value of the `limit` option if set, or `1` for a single effective type.
Fair enough, then it should be 
 Default: Value of the `limit` option if set, or `1` otherwise
Since you already mention above 
> Applied only if effective types contain a single value.

2025-01-08 16:47 UTC, zdila commented on src/types.ts
> +   * Default: Value of the `limit` option if set, or `1` for a single effective type.
Updated.

2025-01-08 16:49 UTC, petr-hajek approved these changes

2025-01-08 16:50 UTC, merged